### ISSUE TITLE
Duplicate management

### ISSUE THREAD

**Issue by zackbatist** [Xunius/MeiTingTrunk#2]
This is a great program, thank you very much for making it! One suggestion I have is to create a mechanism for merging duplicates rather than deleting them. Zotero does this, though I am not really fond of the way that they do it. Rather than having to flip back and forth between two or more records before choosing which one to keep (as is the case with Zotero), perhaps you can implement a way to show the variations of each field and allow the user to select which variant to keep. A new record would then be created to replace the set of duplicates, while all associated data (i.e. notes, paths, etc) would be copied over to the merged replacement record.

You might also be able to make better use of the similarity score by enabling the user to input a threshold value and allow automatic changes to be made to all sets of duplicates beyond that threshold.

**Comment by Xunius** [comment]
Thanks for the feedback.
That's a good point, I didn't think about merging.
I don't have a good solution in mind at the moment. If the difference/variation display is restricted to the few columns shown in a table manner (authors, title, publication, year), that shouldn't be too hard. I could omit a field if it matches with a pre-selected document (onto which the merging is assumed). But if they differ in other fields I would need either a wider table, or something like a vertical diff screen to show the differences. Then comparing more than 2 docs simultaneously would become tricky. I'll have to think about it.
As for the similarity score, I currently don't have too much confidence in the way it is computed (I opened an [issue](#4 ) on this), so I don't think adding an automatic merging would be a good idea, at least before it has been made more robust.
I will drop you a notice after I come up with a solution to the merging problem.

**Comment by zackbatist** [comment]
I have it a bit more thought, specifically thinking how such a hypothetical feature could be implemented alongside what's already in place. Perhaps focus should be on the projected unified record. For each field, the user may be able to select from a dropdown menu that lists the existing variants which the user can choose from. Alternatively they might be given the option to write in a new value or set it to be blank or null. After everything is set up as the user wants it, a “confirm” button would be pressed, similarly to the way you prompt users to confirm the information when adding/editing records regularly. I could envision this somehow being adapted as a way to do batch edits too, like changing authors’ names to account for inconsistently used abbreviations or different uses of upper/lower case in titles.

**Comment by Xunius** [comment]
Thanks for coming back and providing suggestions. I was thinking about something similar, I guess the key would be making the workflow intuitive and fluent.
btw, in terms the file management thing, I'd like to know about your use case of attaching the same file to more than one documents. I'm working on a fix and that kind of confuses me.

**Comment by Xunius** [comment]
Hi @zackbatist ,
I've added the duplicate merging functionality in the latest version (0.1.a12), as we discussed previously the user would pick from a list of unique values and eventually create a unified record. A new document is created from this record and previous ones are sent to trash. If none of the values are correct one can simply edit it in the text edit.

A screenshot:

![Screenshot from 2019-04-07 12-47-03](https://user-images.githubusercontent.com/8076931/55678909-5aea8080-5934-11e9-87bf-575fb99e3697.png)

**Comment by zackbatist** [comment]
It looks and works great! One issue that I identified, however, is when merging more than 2 records, the 'Add to folder(s)' field displays the same folder more than once when two or more instances of the duplicated record are assigned to that folder, and creates a duplicate record for however many checkboxes associated with that folder are checked. For simplicity's sake, it should display each unique associated folder only once.

**Comment by Xunius** [comment]
Hi @zackbatist 
I can't seem to reproduce the error. Did you mean that the same folder name with a checkbox appear more than once? That shouldn't happen as I already removed the duplicate. Even if folders name conflict and the conflicting folders have different parents, they should be distinguished by a path-like string, e.g. folderA/folderB, folderB, folderC/folderB.

**Comment by zackbatist** [comment]
You are right, I think my issues relates to the somewhat hacky way that I tried to update the program to the new build, which resulted in duplicate folders. I tried again with a fresh install and it works fine.

**Comment by Xunius** [comment]
Good to know it works! Feel free to leave more suggestions or bug reports.
