### ISSUE TITLE
File handling

### ISSUE THREAD

**Issue by zackbatist** [Xunius/MeiTingTrunk#3]
My preferred way of organizing my files entails dumping them all into a single folder and associating each one with one or more zotero/MeiTingTrunk records. Based on this preference, here are some suggestions:
- It would be great if the folder where files are saved can be changed to any folder
- Provide the option to delete files from the original location after they have been copied to the target destination (i.e. remove duplicate files clogging up my hard drive)
- Identify when a selected file is already associated with a record, and do not rename the file again or duplicate the file with a new name when such a relationship already exists
- Allow the user to see, and maybe even edit, the entire path under the metadata tab, rather than just displaying the filename and prompting the user to select from a file selection dialog box

**Comment by Xunius** [comment]
Thanks again for the feedbacks.

I just spotted some issues in file handling, as you said it's renaming and recopying existing files. I'll come back to you in a couple of days.

Btw, what's the use case of associating a single file with multiple documents? I actually want to disable this behavior as it would be very annoying to manage them.

**Comment by Xunius** [comment]
I've made some changes to address some of your comments.

I added an option to let user choose whether files would be copied or linked into the library folder. I think this is the easiest fix and would address your first 2 comments. I didn't add the deletion-after-adding option, as that would make it more intrusive, given that I haven't found a reliable way of trashing files using python (see #5 ). Your 4th suggestion is implemented, now the file field is editable, and it will prompt up for error if you input a non-existing file.

As for the 3rd, I still don't understand the rationale behind it. If you want a single doc to appear in multiple "topics", just drag the doc onto multiple folders, the attached files won't get duplicated on disk. But associating a single file to multiple documents seems weird to me. Anyway, now you can, if you so choose, add a file (which is either an actual file or a symbolic link) that's already in the library folder, to another document, but upon saving, it will always create a new copy of the original file (again either by copying the file or making a link). If I allow "direct" association to the same file, then any renaming or deletion will become tricky, it will have to consult all existing associations plus to-be-made associations before doing anything. I think symbolic link is a good compromise, they take up miniature disk spaces, and you can make MTT and Zotero share the same storage.

**Comment by zackbatist** [comment]
I agree that use of symbolic links seems like the best way to deal with this. Would love to test this out but I do not see the option to choose whether files would be copied or linked in the system menus for the most recently updated version.

With regards to my use case, I tend to have unique records for book reviews while also including PDFs of those reviews alongside the record for the book being reviewed. I'm sorry if this is oddly specific, but having this sort of flexibility will likely be beneficial for other similar uses as well.

**Comment by Xunius** [comment]
I see, that's a legit use case that I haven't thought about.
You should be able to see the option in the "Preference -> Savings" dialog, if you obtain the latest master branch, or `pip install` it. The version number is 0.1.a11.

**Comment by zackbatist** [comment]
Can confirm now, works as expected.
